# model
model_name_or_path: 'Salesforce/codegen-350M-mono'
# data
dataset_name: 'openbookqa'
refresh: false
data_tag: 'src'
max_length: 256
prompt_type: 'natural'
# collie
# trainer
tag: 'test'
output_dir: 'output_codegen'
deepspeed: 'ds_config.json'
do_train: true
do_eval: true
evaluation_strategy: 'epoch'
per_device_train_batch_size: 4
per_device_eval_batch_size: 8
learning_rate: 0.005
weight_decay: 0
num_train_epochs: 10
lr_scheduler_type: 'linear'
warmup: 0.05
clip_grad_value: 1.0
#clip_loss_value: 5.0
seed: 42
bf16: true
metric_for_best_model: 'acc'
group_by_length: true
report_to: ''
dataloader_pin_memory: false
gradient_checkpointing: false
train_on_inputs: false
